--liquibase formatted sql
--changeset RustyCrazyPunky:create-tables
CREATE TABLE IF NOT EXISTS SHOPPING_CART_USER (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS SHOPPING_CART (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES SHOPPING_CART_USER (ID)
);

CREATE TABLE IF NOT EXISTS SHOPPING_CART_ITEM (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SHOPPING_CART_ID BIGINT NOT NULL,
    PRODUCT_ID VARCHAR(250) NOT NULL,
    QUANTITY INT NOT NULL,
    FOREIGN KEY (SHOPPING_CART_ID) REFERENCES SHOPPING_CART (ID)
);